name: supnews
description: A new Flutter project.
version: 1.0.2+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  mobx: ^1.2.1+1
  flutter_mobx: ^1.1.0+1
  provider: ^3.0.0
  url_launcher: ^5.0.3
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.3+1
  share: ^0.6.1+1
  intl: ^0.15.8
  hnpwa_client:
  flutter_statusbarcolor: ^0.2.0
  incrementally_loading_listview: ^0.1.0+1
  async:

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^1.1.0+1
  build_runner: ^1.10.0

flutter:
  uses-material-design: true

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Italic.ttf
          style: italic
        - asset: fonts/Lato-Light.ttf
          weight: 300
        - asset: fonts/Lato-Medium.ttf
          weight: 500
